### ISSUE TITLE
structure of the module

### ISSUE THREAD

**Issue by jonasleitner** [h-varma/Team-11#5]
I just commited my thoughts on the inheritance stuff to the class-Branch. And also a quick idea of mine on how to structure the module.
Feel free to change anything and let me know what i missed ;)

**Comment by omzoqasd** [comment]
can we have a quick meeting?

**Comment by jonasleitner** [comment]
sure

**Comment by jonasleitner** [comment]
what software?

**Comment by h-varma** [comment]
I'd also be up for a call

**Comment by omzoqasd** [comment]
i have a heiconf link. how can i share it in private with you both?

**Comment by jonasleitner** [comment]
mail? inga sendet all three of us the team assignment mail

**Comment by h-varma** [comment]
hridya.varma@iwr.uni-heidelberg.de

I think I was assigned to a different group in the beginning

**Comment by omzoqasd** [comment]
thanks for the reminder @jonasleitner

**Comment by omzoqasd** [comment]
some tricks for visual code studio https://code.visualstudio.com/docs/introvideos/versioncontrol

**Comment by jonasleitner** [comment]
@omzoqasd  thanks for the video!

about the task splitting again: 
lets just work all three of us on the module file. When we do rather small commits it should be fine I think. We can think about the main afterwards I would say, but it should be rather simple to write that.

**Comment by omzoqasd** [comment]
thumbs up

**Comment by h-varma** [comment]
Good idea. Let's do it like that.

**Comment by jonasleitner** [comment]
@h-varma I just had a look at your functions in the Numerical class. I don't think you can modify the instance variable in a method like that. I added some lines for testing this below the class. I think we would either need to create a new variable or Define the variable in __init__ like 
self.complex_ar = self.create_complex_matrix(data)

Or am I wrong and there is a way to accomplish that?

**Comment by h-varma** [comment]
> Or am I wrong and there is a way to accomplish that?

In your test, if you do `test_num.create_complex_matrix()` and then print `test_num.data`, it should work. 

Do you prefer to do it differently?

**Comment by jonasleitner** [comment]
ohhhh yes you are right
well I spend my whole morning trying to figure out why this  doesn't work... and as usual there is a very easy solution that I just didn't came up with :D

> Do you prefer to do it differently?

no I think it is great to do it like that (so we don't need to initiate more instances than necessary). Will also adjust the filter method to work like that.
Just one idea: what about using a dict as instance variable and then add an entry "complex_matrix" or sth like that in this case. If we would add the key as function parameter we wouldn't override any data and can access all methods with all variants of data

**Comment by jonasleitner** [comment]
i just changed init and filter_data method of the process class to work with a dictionary.

let me know what you think about it

**Comment by omzoqasd** [comment]
FYI the visual studio code module: "Python Docstring Generator
njpwerner.autodocstring
Nils Werner" 
creats very nicely docstrings. change in settings to sphinx in it is very neat 👍

**Comment by h-varma** [comment]
> Just one idea: what about using a dict as instance variable and then add an entry "complex_matrix" or sth like that in this case. If we would add the key as function parameter we wouldn't override any data and can access all methods with all variants of data

That's a good idea. I just saw your commit. We can do it like that :)

**Comment by omzoqasd** [comment]
how is it with the main.py?

FYI: unit3 is online + needed preparation for Thursday

**Comment by jonasleitner** [comment]
> how is it with the main.py?

guess we can write the main now, since we should have now the structure of the module

> FYI: unit3 is online + needed preparation for Thursday

thanks I will have a look tomorrow :)

**Comment by omzoqasd** [comment]
:-D from my POV, to be honest we may have overengineered the precise functions for the hypothetical science problem. May we focus more on the big picture of the course?

**Comment by h-varma** [comment]
> :-D from my POV, to be honest we may have overengineered the precise functions for the hypothetical science problem. May we focus more on the big picture of the course?

You're totally right. I was just beginning to realize that today :D 
I'm now looking more into understanding sphinx and improving the documentation. Thanks for pointing that out :)
